version: '3.9'
services:
  # API Gateway
  api-gateway:
    container_name: api-gateway
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - mynetwork

  redis:
    image: redis:latest
    container_name: redis_api
    ports:
      - "6385:6379"
    volumes:
      - redis-data:/data
    networks:
      - mynetwork
# Docker Networks
networks:
  mynetwork:
    external: true
    name: global-network
    driver: bridge

# Docker Volumes

volumes:
  db:
  redis-data:
    driver: local