version: '3.9'
services:
  # API Gateway
  api-gateway:
    container_name: api-gateway
    build: .
    ports:
      - "8080:8080"
    networks:
      - mynetwork

# Docker Networks
networks:
  mynetwork:
    external: true
    name: nasiya-network
    driver: bridge

# Docker Volumes

volumes:
  db:
  redis-data:
    driver: local