version: '3.9'
services:
  minio:
    image: docker.io/bitnami/minio:2024
    ports:
      - '3330:3330'
      - '3033:3033'
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=Dior
      - MINIO_ROOT_PASSWORD=isakov05@
      - MINIO_DEFAULT_BUCKETS=photos
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:3330/minio/health/live || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - mynetwork
  
  # API Gateway
  api-gateway-nasiya:
    container_name: api-gateway-nasiya
    build: .
    ports:
      - "3331:3331"
    depends_on:
      - minio
    networks:
      - mynetwork


# Docker Networks
networks:
  mynetwork:
    external: true
    name: nasiya-network
    driver: bridge

# Docker Volumes

volumes:
  db:
  redis-data:
    driver: local
  minio_data:
    driver: local