-- Drop tables
DROP TABLE IF EXISTS exchange CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS transactions CASCADE;
DROP TABLE IF EXISTS notification CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS storage CASCADE;
DROP TABLE IF EXISTS contract CASCADE;

-- Drop ENUM types
DROP TYPE IF EXISTS exchange_status CASCADE;
DROP TYPE IF EXISTS contract_status CASCADE;
