version: '3.8'

services:

  # zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - mynetwork
  
  # kafka
  kafka:
    image: confluentinc/cp-kafka:7.4.4
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    networks:
      - mynetwork
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # redis
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6378:6378"
    volumes:
      - redis_data:/data

  # migrate
  migrate:
    image: migrate/migrate
    networks:
      - mynetwork
    volumes:
      - ./migrations:/migrations
    command: [ "-path", "/migrations", "-database",  
                "postgres://postgres:1234@postgres-nasiya:5432/nasia?sslmode=disable", 
                "up" ]
    depends_on:
      - postgres-db

  # auth-ll
  auth-ll:
    container_name: auth-ll
    build: ./
    depends_on:
      # - postgres-db
      - zookeeper
      - kafka
    ports:
      - "8081:8081"
      - "8082:8082"
    networks:
      - mynetwork

# Docker Networks
networks:
  mynetwork:
    external: true
    name: nasiya-network
    driver: bridge

# Docker Volumes
volumes:
  db:
  redis_data: