version: '3.9'

services:
  notification-service:
    container_name: notification
    build: .
    ports:
      - "3031:3031"
    networks:
      - mynetwork

networks:
  mynetwork:
    external: true
    name: nasiya-network
    driver: bridge
