version: '3.9'

services:
  notification-service:
    container_name: notification
    build: .
    ports:
      - "8089:8089"
    networks:
      - mynetwork

networks:
  mynetwork:
    external: true
    name: nasiya-network
    driver: bridge
