basePath: /
definitions:
  genprotos.AllUsers:
    properties:
      count:
        type: integer
      users:
        items:
          $ref: '#/definitions/genprotos.User'
        type: array
    type: object
  genprotos.ForgotPass:
    properties:
      email:
        type: string
    type: object
  genprotos.User:
    properties:
      address:
        type: string
      created_at:
        type: string
      deleted_at:
        type: integer
      email:
        type: string
      full_name:
        type: string
      id:
        type: string
      password_hash:
        type: string
      phone_number:
        type: string
      updated_at:
        type: string
      username:
        type: string
    type: object
  genprotos.UserLogin:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  genprotos.UserReq:
    properties:
      address:
        type: string
      email:
        type: string
      full_name:
        type: string
      password:
        type: string
      phone_number:
        type: string
      username:
        type: string
    type: object
  handler.VerifyReq:
    properties:
      email:
        type: string
      verifyToken:
        type: string
    type: object
  handler.changePass:
    properties:
      currentPassword:
        type: string
      newPassword:
        type: string
    type: object
  handler.resetPass:
    properties:
      newPassword:
        type: string
      resetToken:
        type: string
    type: object
info:
  contact: {}
  description: auth service API
  title: auth service API
  version: "1.0"
paths:
  /user/change-password:
    post:
      consumes:
      - application/json
      description: Change user password
      parameters:
      - description: Change Password
        in: body
        name: ChangePass
        required: true
        schema:
          $ref: '#/definitions/handler.changePass'
      produces:
      - application/json
      responses:
        "200":
          description: Password Changed Successfully
          schema:
            type: string
        "400":
          description: Error while changing password
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Change Password
      tags:
      - Auth
  /user/delete/{id}:
    delete:
      consumes:
      - application/json
      description: Delete an existing user
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Delete Successful
          schema:
            type: string
        "400":
          description: Error while deleting user
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Delete User
      tags:
      - User
  /user/delete_profil:
    delete:
      consumes:
      - application/json
      description: Delete an existing Profil
      produces:
      - application/json
      responses:
        "200":
          description: Delete Successful
          schema:
            type: string
        "400":
          description: Error while deleting user
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Delete Profil
      tags:
      - User
  /user/forgot-password:
    post:
      consumes:
      - application/json
      description: Initiate forgot password process
      parameters:
      - description: Forgot Password
        in: body
        name: ForgotPass
        required: true
        schema:
          $ref: '#/definitions/genprotos.ForgotPass'
      produces:
      - application/json
      responses:
        "200":
          description: Forgot Password Initiated Successfully
          schema:
            type: string
        "400":
          description: Error while initiating forgot password
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Forgot Password
      tags:
      - Auth
  /user/get_profil:
    get:
      consumes:
      - application/json
      description: Get a user Profil
      produces:
      - application/json
      responses:
        "200":
          description: Get Profil Successful
          schema:
            $ref: '#/definitions/genprotos.User'
        "400":
          description: Error while retrieving user
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Get User Profil
      tags:
      - User
  /user/getall:
    get:
      consumes:
      - application/json
      description: Get all users
      parameters:
      - in: query
        name: address
        type: string
      - in: query
        name: email
        type: string
      - in: query
        name: full_name
        type: string
      - in: query
        name: limit
        type: integer
      - in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Get All Successful
          schema:
            $ref: '#/definitions/genprotos.AllUsers'
        "400":
          description: Error while retrieving users
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Get All Users
      tags:
      - User
  /user/getbyid/{id}:
    get:
      consumes:
      - application/json
      description: Get a user by ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Get By ID Successful
          schema:
            $ref: '#/definitions/genprotos.User'
        "400":
          description: Error while retrieving user
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Get User By ID
      tags:
      - User
  /user/login:
    post:
      consumes:
      - application/json
      description: Login a user
      parameters:
      - description: Create
        in: body
        name: Create
        required: true
        schema:
          $ref: '#/definitions/genprotos.UserLogin'
      produces:
      - application/json
      responses:
        "200":
          description: Login Successful
          schema:
            type: string
        "400":
          description: Error while logging in
          schema:
            type: string
      summary: Login User
      tags:
      - Auth
  /user/refresh-token:
    get:
      consumes:
      - application/json
      description: refresh an existing Token
      produces:
      - application/json
      responses:
        "200":
          description: refresh Successful
          schema:
            type: string
        "400":
          description: Error while refreshed token
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: refresh Toekn
      tags:
      - Auth
  /user/register:
    post:
      consumes:
      - application/json
      description: Register a new user
      parameters:
      - description: Create
        in: body
        name: Create
        required: true
        schema:
          $ref: '#/definitions/genprotos.UserReq'
      produces:
      - application/json
      responses:
        "201":
          description: Create Successful
          schema:
            type: string
        "400":
          description: Error while creating user
          schema:
            type: string
      summary: Register User
      tags:
      - Auth
  /user/reset-password:
    post:
      consumes:
      - application/json
      description: Reset user password
      parameters:
      - description: Reset Password
        in: body
        name: ResetPass
        required: true
        schema:
          $ref: '#/definitions/handler.resetPass'
      produces:
      - application/json
      responses:
        "200":
          description: Password Reset Successfully
          schema:
            type: string
        "400":
          description: Error while resetting password
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Reset Password
      tags:
      - Auth
  /user/update/{id}:
    put:
      consumes:
      - application/json
      description: Update an existing user
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      - description: Update
        in: body
        name: Update
        required: true
        schema:
          $ref: '#/definitions/genprotos.User'
      produces:
      - application/json
      responses:
        "200":
          description: Update Successful
          schema:
            type: string
        "400":
          description: Error while updating user
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Update User
      tags:
      - User
  /user/update_profil:
    put:
      consumes:
      - application/json
      description: Update an existing user
      parameters:
      - description: Update
        in: body
        name: Update
        required: true
        schema:
          $ref: '#/definitions/genprotos.User'
      produces:
      - application/json
      responses:
        "200":
          description: Update Successful
          schema:
            type: string
        "400":
          description: Error while updating user
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Update Profil
      tags:
      - User
  /user/verify_email:
    post:
      consumes:
      - application/json
      description: Verify the user's email and create the account if the token is
        valid
      parameters:
      - description: Verification Request
        in: body
        name: Verify
        required: true
        schema:
          $ref: '#/definitions/handler.VerifyReq'
      produces:
      - application/json
      responses:
        "201":
          description: User created successfully
          schema:
            type: string
        "400":
          description: Invalid token or verification failed
          schema:
            type: string
      summary: Verify User Email
      tags:
      - Auth
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
